<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('permissions')->truncate();

        $permissions = [
            // Dashboard
            [
                'name' => 'dashboard.view',
                'display_name' => 'View Dashboard',
                'description' => 'Permission to view dashboard',
                'module' => 'dashboard',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Access Control > Users
            [
                'name' => 'access-control.users.view',
                'display_name' => 'View Users',
                'description' => 'Permission to view users',
                'module' => 'users',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.users.create',
                'display_name' => 'Create User',
                'description' => 'Permission to create new user',
                'module' => 'users',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.users.update',
                'display_name' => 'Update User',
                'description' => 'Permission to update user',
                'module' => 'users',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.users.delete',
                'display_name' => 'Delete User',
                'description' => 'Permission to delete user',
                'module' => 'users',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Access Control > Roles
            [
                'name' => 'access-control.roles.view',
                'display_name' => 'View Roles',
                'description' => 'Permission to view roles',
                'module' => 'roles',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.roles.create',
                'display_name' => 'Create Role',
                'description' => 'Permission to create new role',
                'module' => 'roles',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.roles.update',
                'display_name' => 'Update Role',
                'description' => 'Permission to update role',
                'module' => 'roles',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.roles.delete',
                'display_name' => 'Delete Role',
                'description' => 'Permission to delete role',
                'module' => 'roles',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Access Control > Permissions
            [
                'name' => 'access-control.permissions.view',
                'display_name' => 'View Permissions',
                'description' => 'Permission to view permissions',
                'module' => 'permissions',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.permissions.create',
                'display_name' => 'Create Permission',
                'description' => 'Permission to create new permission',
                'module' => 'permissions',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.permissions.update',
                'display_name' => 'Update Permission',
                'description' => 'Permission to update permission',
                'module' => 'permissions',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.permissions.delete',
                'display_name' => 'Delete Permission',
                'description' => 'Permission to delete permission',
                'module' => 'permissions',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Access Control > Modules
            [
                'name' => 'access-control.modules.view',
                'display_name' => 'View Modules',
                'description' => 'Permission to view modules',
                'module' => 'modules',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.modules.create',
                'display_name' => 'Create Module',
                'description' => 'Permission to create new module',
                'module' => 'modules',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.modules.update',
                'display_name' => 'Update Module',
                'description' => 'Permission to update module',
                'module' => 'modules',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.modules.delete',
                'display_name' => 'Delete Module',
                'description' => 'Permission to delete module',
                'module' => 'modules',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Access Control > User Activities
            [
                'name' => 'access-control.user-activities.view',
                'display_name' => 'View User Activities',
                'description' => 'Permission to view user activities',
                'module' => 'user-activities',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.user-activities.export',
                'display_name' => 'Export User Activities',
                'description' => 'Permission to export user activities',
                'module' => 'user-activities',
                'action' => 'export',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'access-control.user-activities.clear',
                'display_name' => 'Clear User Activities',
                'description' => 'Permission to clear all user activities',
                'module' => 'user-activities',
                'action' => 'clear',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Generals > Store Info
            [
                'name' => 'settings.generals.store.view',
                'display_name' => 'View Store Info',
                'description' => 'Permission to view store information settings',
                'module' => 'store',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.generals.store.update',
                'display_name' => 'Update Store Info',
                'description' => 'Permission to update store information settings',
                'module' => 'store',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Generals > Email Settings
            [
                'name' => 'settings.generals.email.view',
                'display_name' => 'View Email Settings',
                'description' => 'Permission to view email settings',
                'module' => 'email',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.generals.email.update',
                'display_name' => 'Update Email Settings',
                'description' => 'Permission to update email settings',
                'module' => 'email',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Generals > SEO & Meta
            [
                'name' => 'settings.generals.seo.view',
                'display_name' => 'View SEO Settings',
                'description' => 'Permission to view SEO and meta settings',
                'module' => 'seo',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.generals.seo.update',
                'display_name' => 'Update SEO Settings',
                'description' => 'Permission to update SEO and meta settings',
                'module' => 'seo',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Generals > System Config
            [
                'name' => 'settings.generals.system.view',
                'display_name' => 'View System Config',
                'description' => 'Permission to view system configuration',
                'module' => 'system',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.generals.system.update',
                'display_name' => 'Update System Config',
                'description' => 'Permission to update system configuration',
                'module' => 'system',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Generals > API Tokens
            [
                'name' => 'settings.generals.api-tokens.view',
                'display_name' => 'View API Tokens',
                'description' => 'Permission to view API tokens',
                'module' => 'api-tokens',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.generals.api-tokens.generate',
                'display_name' => 'Generate API Tokens',
                'description' => 'Permission to generate API tokens',
                'module' => 'api-tokens',
                'action' => 'generate',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.generals.api-tokens.revoke',
                'display_name' => 'Revoke API Tokens',
                'description' => 'Permission to revoke API tokens',
                'module' => 'api-tokens',
                'action' => 'revoke',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Payments > Payment Methods
            [
                'name' => 'settings.payments.methods.view',
                'display_name' => 'View Payment Methods',
                'description' => 'Permission to view payment methods',
                'module' => 'payment-methods',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.payments.methods.update',
                'display_name' => 'Update Payment Methods',
                'description' => 'Permission to update payment methods',
                'module' => 'payment-methods',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Payments > Midtrans Config
            [
                'name' => 'settings.payments.midtrans.view',
                'display_name' => 'View Midtrans Config',
                'description' => 'Permission to view Midtrans configuration',
                'module' => 'midtrans-config',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.payments.midtrans.update',
                'display_name' => 'Update Midtrans Config',
                'description' => 'Permission to update Midtrans configuration',
                'module' => 'midtrans-config',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Payments > Tax Settings
            [
                'name' => 'settings.payments.tax.view',
                'display_name' => 'View Tax Settings',
                'description' => 'Permission to view tax settings',
                'module' => 'tax-settings',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.payments.tax.update',
                'display_name' => 'Update Tax Settings',
                'description' => 'Permission to update tax settings',
                'module' => 'tax-settings',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Shippings > Shipping Methods
            [
                'name' => 'settings.shippings.methods.view',
                'display_name' => 'View Shipping Methods',
                'description' => 'Permission to view shipping methods',
                'module' => 'shipping-methods',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.shippings.methods.update',
                'display_name' => 'Update Shipping Methods',
                'description' => 'Permission to update shipping methods',
                'module' => 'shipping-methods',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Shippings > RajaOngkir Config
            [
                'name' => 'settings.shippings.rajaongkir.view',
                'display_name' => 'View RajaOngkir Config',
                'description' => 'Permission to view RajaOngkir configuration',
                'module' => 'rajaongkir-config',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.shippings.rajaongkir.update',
                'display_name' => 'Update RajaOngkir Config',
                'description' => 'Permission to update RajaOngkir configuration',
                'module' => 'rajaongkir-config',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings > Shippings > Origin Address
            [
                'name' => 'settings.shippings.origin.view',
                'display_name' => 'View Origin Address',
                'description' => 'Permission to view origin address',
                'module' => 'origin-address',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'settings.shippings.origin.update',
                'display_name' => 'Update Origin Address',
                'description' => 'Permission to update origin address',
                'module' => 'origin-address',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Catalog > Products > All Product
            [
                'name' => 'catalog.products.all-products.view',
                'display_name' => 'View All Products',
                'description' => 'Permission to view all products',
                'module' => 'all-products',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.all-products.create',
                'display_name' => 'Create Product',
                'description' => 'Permission to create new product',
                'module' => 'all-products',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.all-products.update',
                'display_name' => 'Update Product',
                'description' => 'Permission to update product',
                'module' => 'all-products',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.all-products.delete',
                'display_name' => 'Delete Product',
                'description' => 'Permission to delete product',
                'module' => 'all-products',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Catalog > Products > Add Product
            [
                'name' => 'catalog.products.add-products.view',
                'display_name' => 'View Add Products',
                'description' => 'Permission to view add products',
                'module' => 'add-products',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Catalog > Products > Categories
            [
                'name' => 'catalog.products.categories.view',
                'display_name' => 'View Categories',
                'description' => 'Permission to view categories',
                'module' => 'categories',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.categories.create',
                'display_name' => 'Create Category',
                'description' => 'Permission to create new category',
                'module' => 'categories',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.categories.update',
                'display_name' => 'Update Category',
                'description' => 'Permission to update category',
                'module' => 'categories',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.categories.delete',
                'display_name' => 'Delete Category',
                'description' => 'Permission to delete category',
                'module' => 'categories',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Catalog > Products > Brands
            [
                'name' => 'catalog.products.brands.view',
                'display_name' => 'View Brands',
                'description' => 'Permission to view brands',
                'module' => 'brands',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.brands.create',
                'display_name' => 'Create Brand',
                'description' => 'Permission to create new brand',
                'module' => 'brands',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.brands.update',
                'display_name' => 'Update Brand',
                'description' => 'Permission to update brand',
                'module' => 'brands',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.brands.delete',
                'display_name' => 'Delete Brand',
                'description' => 'Permission to delete brand',
                'module' => 'brands',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Catalog > Products > Variants
            [
                'name' => 'catalog.products.variants.view',
                'display_name' => 'View Variants',
                'description' => 'Permission to view product variants',
                'module' => 'variants',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.variants.create',
                'display_name' => 'Create Variant',
                'description' => 'Permission to create new product variant',
                'module' => 'variants',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.variants.update',
                'display_name' => 'Update Variant',
                'description' => 'Permission to update product variant',
                'module' => 'variants',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'catalog.products.variants.delete',
                'display_name' => 'Delete Variant',
                'description' => 'Permission to delete product variant',
                'module' => 'variants',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Reports > Sales Report
            [
                'name' => 'reports.sales.view',
                'display_name' => 'View Sales Report',
                'description' => 'Permission to view sales report',
                'module' => 'sales-report',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'reports.sales.export',
                'display_name' => 'Export Sales Report',
                'description' => 'Permission to export sales report',
                'module' => 'sales-report',
                'action' => 'export',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Reports > Revenue Report
            [
                'name' => 'reports.revenue.view',
                'display_name' => 'View Revenue Report',
                'description' => 'Permission to view revenue report',
                'module' => 'revenue-report',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'reports.revenue.export',
                'display_name' => 'Export Revenue Report',
                'description' => 'Permission to export revenue report',
                'module' => 'revenue-report',
                'action' => 'export',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Reports > Product Performance
            [
                'name' => 'reports.product-performance.view',
                'display_name' => 'View Product Performance',
                'description' => 'Permission to view product performance report',
                'module' => 'product-performance',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'reports.product-performance.export',
                'display_name' => 'Export Product Performance',
                'description' => 'Permission to export product performance report',
                'module' => 'product-performance',
                'action' => 'export',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Reports > Inventory Report
            [
                'name' => 'reports.inventory.view',
                'display_name' => 'View Inventory Report',
                'description' => 'Permission to view inventory report',
                'module' => 'inventory-report',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'reports.inventory.export',
                'display_name' => 'Export Inventory Report',
                'description' => 'Permission to export inventory report',
                'module' => 'inventory-report',
                'action' => 'export',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customers > All Customers
            [
                'name' => 'customers.all-customers.view',
                'display_name' => 'View All Customers',
                'description' => 'Permission to view all customers',
                'module' => 'all-customers',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.all-customers.create',
                'display_name' => 'Create Customer',
                'description' => 'Permission to create customer',
                'module' => 'all-customers',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.all-customers.update',
                'display_name' => 'Update Customer',
                'description' => 'Permission to update customer',
                'module' => 'all-customers',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.all-customers.delete',
                'display_name' => 'Delete Customer',
                'description' => 'Permission to delete customer',
                'module' => 'all-customers',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.all-customers.export',
                'display_name' => 'Export Customers',
                'description' => 'Permission to export customers',
                'module' => 'all-customers',
                'action' => 'export',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customers > Customer Segments
            [
                'name' => 'customers.customer-segments.view',
                'display_name' => 'View Customer Segments',
                'description' => 'Permission to view customer segments',
                'module' => 'customer-segments',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.customer-segments.create',
                'display_name' => 'Create Customer Segment',
                'description' => 'Permission to create customer segment',
                'module' => 'customer-segments',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.customer-segments.update',
                'display_name' => 'Update Customer Segment',
                'description' => 'Permission to update customer segment',
                'module' => 'customer-segments',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.customer-segments.delete',
                'display_name' => 'Delete Customer Segment',
                'description' => 'Permission to delete customer segment',
                'module' => 'customer-segments',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customers > VIP Customers
            [
                'name' => 'customers.vip-customers.view',
                'display_name' => 'View VIP Customers',
                'description' => 'Permission to view VIP customers',
                'module' => 'vip-customers',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.vip-customers.manage',
                'display_name' => 'Manage VIP Status',
                'description' => 'Permission to manage VIP customer status',
                'module' => 'vip-customers',
                'action' => 'manage',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customers > Customer Groups
            [
                'name' => 'customers.customer-groups.view',
                'display_name' => 'View Customer Groups',
                'description' => 'Permission to view customer groups',
                'module' => 'customer-groups',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.customer-groups.create',
                'display_name' => 'Create Customer Group',
                'description' => 'Permission to create customer group',
                'module' => 'customer-groups',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.customer-groups.update',
                'display_name' => 'Update Customer Group',
                'description' => 'Permission to update customer group',
                'module' => 'customer-groups',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.customer-groups.delete',
                'display_name' => 'Delete Customer Group',
                'description' => 'Permission to delete customer group',
                'module' => 'customer-groups',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customers > Loyalty Programs
            [
                'name' => 'customers.loyalty.view',
                'display_name' => 'View Loyalty Programs',
                'description' => 'Permission to view loyalty programs',
                'module' => 'loyalty',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.loyalty.create',
                'display_name' => 'Create Loyalty Program',
                'description' => 'Permission to create loyalty program',
                'module' => 'loyalty',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.loyalty.update',
                'display_name' => 'Update Loyalty Program',
                'description' => 'Permission to update loyalty program',
                'module' => 'loyalty',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.loyalty.delete',
                'display_name' => 'Delete Loyalty Program',
                'description' => 'Permission to delete loyalty program',
                'module' => 'loyalty',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customers > Reviews
            [
                'name' => 'customers.reviews.view',
                'display_name' => 'View Customer Reviews',
                'description' => 'Permission to view customer reviews',
                'module' => 'reviews',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.reviews.approve',
                'display_name' => 'Approve Customer Reviews',
                'description' => 'Permission to approve customer reviews',
                'module' => 'reviews',
                'action' => 'approve',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.reviews.update',
                'display_name' => 'Update Customer Reviews',
                'description' => 'Permission to update and respond to customer reviews',
                'module' => 'reviews',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'customers.reviews.delete',
                'display_name' => 'Delete Customer Reviews',
                'description' => 'Permission to delete customer reviews',
                'module' => 'reviews',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Marketing > Coupons
            [
                'name' => 'marketing.coupons.view',
                'display_name' => 'View Coupons',
                'description' => 'Permission to view coupons',
                'module' => 'coupons',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.coupons.create',
                'display_name' => 'Create Coupon',
                'description' => 'Permission to create coupon',
                'module' => 'coupons',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.coupons.update',
                'display_name' => 'Update Coupon',
                'description' => 'Permission to update coupon',
                'module' => 'coupons',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.coupons.delete',
                'display_name' => 'Delete Coupon',
                'description' => 'Permission to delete coupon',
                'module' => 'coupons',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Marketing > Flash Sales
            [
                'name' => 'marketing.flash-sales.view',
                'display_name' => 'View Flash Sales',
                'description' => 'Permission to view flash sales',
                'module' => 'flash-sales',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.flash-sales.create',
                'display_name' => 'Create Flash Sale',
                'description' => 'Permission to create flash sale',
                'module' => 'flash-sales',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.flash-sales.update',
                'display_name' => 'Update Flash Sale',
                'description' => 'Permission to update flash sale',
                'module' => 'flash-sales',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.flash-sales.delete',
                'display_name' => 'Delete Flash Sale',
                'description' => 'Permission to delete flash sale',
                'module' => 'flash-sales',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Marketing > Bundle Deals
            [
                'name' => 'marketing.bundle-deals.view',
                'display_name' => 'View Bundle Deals',
                'description' => 'Permission to view bundle deals',
                'module' => 'bundle-deals',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.bundle-deals.create',
                'display_name' => 'Create Bundle Deal',
                'description' => 'Permission to create bundle deal',
                'module' => 'bundle-deals',
                'action' => 'create',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.bundle-deals.update',
                'display_name' => 'Update Bundle Deal',
                'description' => 'Permission to update bundle deal',
                'module' => 'bundle-deals',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'marketing.bundle-deals.delete',
                'display_name' => 'Delete Bundle Deal',
                'description' => 'Permission to delete bundle deal',
                'module' => 'bundle-deals',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Orders > All Orders
            [
                'name' => 'orders.all-orders.view',
                'display_name' => 'View All Orders',
                'description' => 'Permission to view all orders',
                'module' => 'all-orders',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'orders.all-orders.update',
                'display_name' => 'Update Order',
                'description' => 'Permission to update order',
                'module' => 'all-orders',
                'action' => 'update',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'orders.all-orders.delete',
                'display_name' => 'Delete Order',
                'description' => 'Permission to delete order',
                'module' => 'all-orders',
                'action' => 'delete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'orders.all-orders.export',
                'display_name' => 'Export Orders',
                'description' => 'Permission to export orders',
                'module' => 'all-orders',
                'action' => 'export',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Orders > Pending Orders
            [
                'name' => 'orders.pending-orders.view',
                'display_name' => 'View Pending Orders',
                'description' => 'Permission to view pending orders',
                'module' => 'pending-orders',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'orders.pending-orders.confirm',
                'display_name' => 'Confirm Pending Order',
                'description' => 'Permission to confirm pending order',
                'module' => 'pending-orders',
                'action' => 'confirm',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'orders.pending-orders.cancel',
                'display_name' => 'Cancel Pending Order',
                'description' => 'Permission to cancel pending order',
                'module' => 'pending-orders',
                'action' => 'cancel',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Orders > Processing Orders
            [
                'name' => 'orders.processing-orders.view',
                'display_name' => 'View Processing Orders',
                'description' => 'Permission to view processing orders',
                'module' => 'processing-orders',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'orders.processing-orders.ship',
                'display_name' => 'Ship Processing Order',
                'description' => 'Permission to ship processing order',
                'module' => 'processing-orders',
                'action' => 'ship',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Orders > Shipped Orders
            [
                'name' => 'orders.shipped-orders.view',
                'display_name' => 'View Shipped Orders',
                'description' => 'Permission to view shipped orders',
                'module' => 'shipped-orders',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'orders.shipped-orders.complete',
                'display_name' => 'Complete Shipped Order',
                'description' => 'Permission to complete shipped order',
                'module' => 'shipped-orders',
                'action' => 'complete',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Orders > Completed Orders
            [
                'name' => 'orders.completed-orders.view',
                'display_name' => 'View Completed Orders',
                'description' => 'Permission to view completed orders',
                'module' => 'completed-orders',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Orders > Cancelled Orders
            [
                'name' => 'orders.cancelled-orders.view',
                'display_name' => 'View Cancelled Orders',
                'description' => 'Permission to view cancelled orders',
                'module' => 'cancelled-orders',
                'action' => 'view',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('permissions')->insert($permissions);

        $this->command->info('Permissions seeded successfully.');
    }
}
